import React from 'react';
import { AlertTriangle, CheckCircle2, Target, Network, ScrollText, Fingerprint, RefreshCcw } from 'lucide-react';
import { DecisionAnalysis, Assumption, ImpactLevel, UncertaintyLevel } from '../types';
import { AssumptionMatrix } from './AssumptionMatrix';

interface DashboardProps {
  analysis: DecisionAnalysis;
  onReset: () => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ analysis, onReset }) => {
  return (
    <div className="w-full max-w-7xl mx-auto pb-20">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8 animate-fade-in-up">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight">Decomposition Report</h1>
          <p className="text-slate-400 mt-1">Generated by Decision Decomposer Agent</p>
        </div>
        <button 
          onClick={onReset}
          className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg border border-slate-700 transition-colors"
        >
          <RefreshCcw className="w-4 h-4" />
          New Analysis
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Column 1: Summary & Claims */}
        <div className="space-y-6 lg:col-span-1">
          {/* Summary Card */}
          <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-sm">
            <h3 className="text-sm uppercase tracking-wider font-semibold text-slate-400 mb-4 flex items-center gap-2">
              <ScrollText className="w-4 h-4" />
              Decision Summary
            </h3>
            <p className="text-lg text-white font-medium leading-relaxed">
              {analysis.decision_summary}
            </p>
          </div>

          {/* Claims Card */}
          <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-sm">
            <h3 className="text-sm uppercase tracking-wider font-semibold text-slate-400 mb-4 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4" />
              Strategic Claims
            </h3>
            <ul className="space-y-3">
              {analysis.claims.map((claim, idx) => (
                <li key={idx} className="flex gap-3 text-slate-300 text-sm">
                  <span className="text-indigo-400 font-bold mt-0.5">•</span>
                  {claim}
                </li>
              ))}
            </ul>
          </div>

           {/* Evidence Card */}
           {analysis.evidence.length > 0 && (
            <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-sm">
              <h3 className="text-sm uppercase tracking-wider font-semibold text-slate-400 mb-4 flex items-center gap-2">
                <ScrollText className="w-4 h-4" />
                Supporting Evidence
              </h3>
              <ul className="space-y-3">
                {analysis.evidence.map((ev, idx) => (
                  <li key={idx} className="bg-slate-900/50 p-3 rounded border-l-2 border-indigo-500 text-slate-400 text-xs italic">
                    "{ev}"
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* Column 2: KPIs & Assumptions */}
        <div className="space-y-6 lg:col-span-1">
           {/* KPIs */}
           <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-sm">
            <h3 className="text-sm uppercase tracking-wider font-semibold text-slate-400 mb-4 flex items-center gap-2">
              <Target className="w-4 h-4" />
              Measurable KPIs
            </h3>
            <div className="space-y-4">
              {analysis.kpis.map((kpi, idx) => (
                <div key={idx} className="bg-slate-900 rounded-lg p-4 border border-slate-700/50">
                  <div className="text-indigo-400 font-semibold mb-2">{kpi.name}</div>
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div>
                      <span className="block text-slate-500">Baseline</span>
                      <span className="text-slate-300">{kpi.baseline || "N/A"}</span>
                    </div>
                    <div className="text-right">
                      <span className="block text-slate-500">Target</span>
                      <span className="text-emerald-400 font-bold">{kpi.target || "N/A"}</span>
                    </div>
                  </div>
                  {kpi.time_horizon && (
                     <div className="mt-2 pt-2 border-t border-slate-800 text-xs text-slate-500 flex justify-between">
                       <span>Time Horizon</span>
                       <span>{kpi.time_horizon}</span>
                     </div>
                  )}
                </div>
              ))}
              {analysis.kpis.length === 0 && (
                <p className="text-slate-500 text-sm italic">No specific KPIs identified.</p>
              )}
            </div>
          </div>

          {/* Assumptions Matrix */}
          <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-sm">
            <h3 className="text-sm uppercase tracking-wider font-semibold text-slate-400 mb-4 flex items-center gap-2">
               <Fingerprint className="w-4 h-4" />
               Assumptions Landscape
            </h3>
            <AssumptionMatrix assumptions={analysis.assumptions} />
            
            <div className="mt-6 space-y-3 max-h-60 overflow-y-auto pr-2 custom-scrollbar">
              {analysis.assumptions.map((assump, idx) => (
                <div key={idx} className="text-xs border-b border-slate-700/50 last:border-0 pb-2 last:pb-0">
                  <div className="flex justify-between mb-1">
                    <span className={`uppercase font-bold text-[10px] px-1.5 py-0.5 rounded 
                      ${assump.type === 'explicit' ? 'bg-blue-900/30 text-blue-400' : 'bg-purple-900/30 text-purple-400'}`}>
                      {assump.type}
                    </span>
                    <div className="flex gap-2">
                       <span className={`text-[10px] ${assump.impact_level === ImpactLevel.High ? 'text-red-400 font-bold' : 'text-slate-500'}`}>
                         Imp: {assump.impact_level}
                       </span>
                       <span className={`text-[10px] ${assump.uncertainty_level === UncertaintyLevel.High ? 'text-orange-400 font-bold' : 'text-slate-500'}`}>
                         Unc: {assump.uncertainty_level}
                       </span>
                    </div>
                  </div>
                  <p className="text-slate-300">{assump.text}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Column 3: Risks, Dependencies & Thoughts */}
        <div className="space-y-6 lg:col-span-1">
          {/* Risks */}
          <div className="bg-slate-800 rounded-xl p-6 border border-red-900/30 shadow-sm relative overflow-hidden">
            <div className="absolute top-0 right-0 w-24 h-24 bg-red-500/5 blur-[50px] rounded-full"></div>
            <h3 className="text-sm uppercase tracking-wider font-semibold text-red-400 mb-4 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4" />
              Identified Risks
            </h3>
            <ul className="space-y-3">
              {analysis.risks.map((risk, idx) => (
                <li key={idx} className="flex gap-3 text-slate-300 text-sm">
                  <span className="text-red-500 font-bold mt-0.5">!</span>
                  {risk}
                </li>
              ))}
            </ul>
          </div>

          {/* Dependencies */}
          <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-sm">
            <h3 className="text-sm uppercase tracking-wider font-semibold text-slate-400 mb-4 flex items-center gap-2">
              <Network className="w-4 h-4" />
              Dependencies
            </h3>
            <div className="flex flex-wrap gap-2">
              {analysis.dependencies.map((dep, idx) => (
                <span key={idx} className="px-3 py-1 bg-slate-900 text-slate-300 text-xs rounded-full border border-slate-700">
                  {dep}
                </span>
              ))}
            </div>
          </div>

          {/* Thought Signature */}
          <div className="bg-slate-900/80 rounded-xl p-6 border border-slate-800">
             <h3 className="text-xs uppercase tracking-wider font-bold text-slate-600 mb-3">Agent Thought Process</h3>
             <ul className="space-y-2">
               {analysis.thought_signature.map((thought, idx) => (
                 <li key={idx} className="text-xs text-slate-500 font-mono flex gap-2">
                   <span className="text-slate-700">{idx + 1}.</span>
                   {thought}
                 </li>
               ))}
             </ul>
          </div>
        </div>

      </div>
    </div>
  );
};